# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21ce4162c17043d49996229053d2563ca1164d20cf781d87ebad41bdff44620b2d4b1ad088a062acb1f8fd2a0f1cc0595a2ca5864aa76e40c64bdbced4b980b7

test:
  secret_key_base: 7cf2313960e20949b88f816c668cb355c1e1d5d8188ef1335ffc6ef62b5e3b3f108fc730e4d1771fe60ba17a6b3e926a53994e6d707d75821f608e1a6b287945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
